config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  ActiveAdmin.routes(self)

  root 'home_page#index'

  resources :users, only: [:show] do
    resources :albums, except: [:index] do
      resources :photos, except: [:index] do
        resources :comments, only: [:create, :destroy]
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :interrelationships, only: [:create, :destroy]

  get 'search', to: 'search#search', autocomplete: true
  get 'tag_search', to: 'search#tag_search', autocomplete: true

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  photo_id   :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_photo_id  (photo_id)
#  index_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (photo_id => photos.id)
#  fk_rails_...  (user_id => users.id)
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :album, through: :user
  load_and_authorize_resource :photo, through: :album
  load_and_authorize_resource through: :photo

  def create
    @comment.user = current_user
    Notifications::NotifyComment.new(@comment).notify if @comment.save
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.slim
- comment ||= @comment
.comment(id="comment#{comment.id}")
  .comment-container.DivToScroll
    .container-fluid
      .row.flex-comments
        div
          = link_to user_path(comment.user)
            - if comment.user.avatar.url.present?
              = image_tag comment.user.avatar, class: 'photo-preview'
        div
          = comment.user.display_name
        div
          - if can? :destroy, comment
            = link_to user_album_photo_comment_path(@user, @album, @photo, comment),
                      method: :delete, data: { confirm: 'Are you sure?' },
                      :class => 'btn btn-xs btn-danger',
                      remote: true do
                span.glyphicon.glyphicon-minus aria-hidden="true"
      .row
        .col-md-12
          = comment.content
    = time_ago_in_words(comment.created_at)
    |  ago.

app/views/comments/_form.html.slim
div
  = simple_form_for :comment, url: user_album_photo_comments_path(@user, @album, @photo), remote: true do |f|
    .input-group
      = f.input :content, placeholder: "Compose new comment", class: "form-control", required: true, label: false, maxlength: 140
      = f.submit "Post", class: "btn btn-primary"

app/views/comments/create.js.erb
$("<%= escape_javascript(render @comment) %>").appendTo('.comments');
$('#comment_content').val('');
$(".comments").animate({ scrollTop: $('.comments')[0].scrollHeight }, "slow");

app/views/comments/destroy.js.erb
$(".comment#comment<%= @comment.id %>").remove();