config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  ActiveAdmin.routes(self)

  root 'home_page#index'

  resources :users, only: [:show] do
    resources :albums, except: [:index] do
      resources :photos, except: [:index] do
        resources :comments, only: [:create, :destroy]
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :interrelationships, only: [:create, :destroy]

  get 'search', to: 'search#search', autocomplete: true
  get 'tag_search', to: 'search#tag_search', autocomplete: true

  mount ActionCable.server => '/cable'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  adress                 :string
#  avatar                 :string
#  role                   :string           default("user"), not null
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :role, presence: true
  validates :first_name, :last_name, presence: true, length: { maximum: 30 }
  validates :adress, length: { maximum: 100 }

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_interrelationships, class_name:  "Interrelationship",
                                    foreign_key: "follower_id",
                                    dependent:   :destroy
  has_many :passive_interrelationships, class_name:  "Interrelationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :following, through: :active_interrelationships, source: :followed
  has_many :followers, through: :passive_interrelationships, source: :follower

  has_many :photos, through: :albums, source: :photos
  has_many :feed_photos, through: :following, source: :photos

  mount_uploader :avatar, AvatarUploader
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  def following?(other_user)
    following.include?(other_user)
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :first_name
      indexes :last_name
    end
  end

  def display_name
    first_name + " " + last_name
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
    @albums = @user.albums
  end
end

app/views/users/_follow.html.slim
- followed = @user || @interrelationship.followed
= form_for(current_user.active_interrelationships.build(followed_id: followed.id), remote: true) do |f|
  = hidden_field_tag :followed_id, followed.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
#follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/users/_unfollow.html.slim
- followed = @user || @interrelationship.followed
= form_for(current_user.active_interrelationships.find_by(followed_id: followed.id),
                                  html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-primary"

app/views/users/show.html.slim
- model_class = User
.container
  .row
    .col-md-4.col-lg-3.col-sm-6
      .center
        .avatar.avatar-border
          - if @user.avatar.url
            = image_tag @user.avatar
          - else
            = image_tag '/avatar_empty.png'
        = @user.display_name
        - if can?(:create, Interrelationship.new(follower: current_user, followed: @user))
          = render 'follow_form'
        div
          = @user.followers.count
          |  followers
        div
          = @user.following.count
          |  following
    .col-md-8.col-lg-9.col-sm-6
      .center
        - if can? :create, @user, @album
          = link_to "New Album", new_user_album_path(@user), class: 'btn btn-primary'
      .row
        = render @user.albums