config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  ActiveAdmin.routes(self)

  root 'home_page#index'

  resources :users, only: [:show] do
    resources :albums, except: [:index] do
      resources :photos, except: [:index] do
        resources :comments, only: [:create, :destroy]
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :interrelationships, only: [:create, :destroy]

  get 'search', to: 'search#search', autocomplete: true
  get 'tag_search', to: 'search#tag_search', autocomplete: true

  mount ActionCable.server => '/cable'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_albums_on_user_id                 (user_id)
#  index_albums_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Album < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  validates :photos, length: { maximum: 50 }
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 140 }

  def tags=(tags)
    super
    __elasticsearch__.index_document
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title
      indexes :description
      indexes :tags, type: "nested" do
        indexes :content
      end
    end
  end

  def as_indexed_json(_ = nil)
    as_json(include: { tags: { only: :content } }, except:  %i[id _id])
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource through: :user

  def new
  end

  def show
    @tags = @album.tags
    @photos = @album.photos
  end

  def edit
  end

  def update
    @album.tags = TagService.new(params[:album][:tags]).tags if @album.update_attributes(album_params)
    album_respond
  end

  def create
    @album.tags = TagService.new(params[:album][:tags]).tags if @album.save
    album_respond
  end

  def destroy
    @album.destroy
    respond_with @album, location: -> { user_path(@user) }
  end

  private

  def album_params
    params.require(:album).permit(:title, :description)
  end

  def album_respond
    respond_with @album, location: -> { user_album_path(@user, @album) }
  end
end

app/views/albums/_album.html.slim
.col-md-4.col-sm-6.col-lg-4.col-xs-12
  h2.center
    = album.title
  div
    = link_to user_album_path(@user, album)
      .album-collage
        - urls = album.photos.first(4).map { |photo| photo.image.thumb.url }
        - urls.push('/blank_photo.png') while urls.size < 4
        - urls.each do |url|
          .col-md-6.col-sm-6.col-lg-6.col-xs-6
            .row
              .album-preview-item style="background-image: url(#{url})"

app/views/albums/_form.html.slim
- tags = @album.tags.map { |tag| { id: tag.content, text: tag.content , selected: true } }
.col-md-6.col-md-offset-3
  = simple_form_for @album, url: url do |f|
    = f.error_notification
    .form-inputs
      = f.input :title, required: true, autofocus: true
      = f.input :description
      = f.input :tags, as: :select, input_html: { id: 'tags', multiple: true,
                                                  data: { tags: tags, width: '100%' } },
                                                  collection: [], include_blank: false,
                                                  include_hidden: false
    .form-actions.flex-buttons
      = link_to "Back", :back, class: 'btn btn-default'
      = f.button :submit, class: 'btn btn-success'

app/views/albums/edit.html.slim
- model_class = Album
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render 'form', url: user_album_path(@user, @album)

app/views/albums/new.html.slim
- model_class = Album
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render 'form', url: user_albums_path(@user)

app/views/albums/show.html.slim
- model_class = Album
.container
  .flex-buttons
    div
      - if can? :create, @album, @photo
        = link_to "New Photo", new_user_album_photo_path(@user, @album), class: 'btn btn-primary'
    div
      - if can? :update, @album
        = link_to "Edit Album", edit_user_album_path(@user, @album), class: 'btn btn-default'
    div
      - if can? :destroy, @album
        = link_to "Delete Album", user_album_path(@user, @album), method: :delete,
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger'
  .center
    h3
      = @album.title
    h4
      = @album.description
    h4
      = render @tags if @tags
    = render @photos
  .modal.fade