config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  ActiveAdmin.routes(self)

  root 'home_page#index'

  resources :users, only: [:show] do
    resources :albums, except: [:index] do
      resources :photos, except: [:index] do
        resources :comments, only: [:create, :destroy]
      end
    end
    member do
      get :following, :followers
    end
  end

  resources :interrelationships, only: [:create, :destroy]

  get 'search', to: 'search#search', autocomplete: true
  get 'tag_search', to: 'search#tag_search', autocomplete: true

  mount ActionCable.server => '/cable'
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  image       :string
#  description :text
#  album_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_photos_on_album_id                 (album_id)
#  index_photos_on_album_id_and_created_at  (album_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (album_id => albums.id)
#

class Photo < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :album
  has_many :comments, dependent: :destroy
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  mount_uploader :image, PictureUploader
  validates_integrity_of  :image
  validates_processing_of :image

  validates :image, presence: true
  validates :description, length: { maximum: 140 }

  settings index: { number_of_shards: 1 } do
    mappings dynamic: "false" do
      indexes :description
      indexes :tags, type: 'nested' do
        indexes :content
      end
    end
  end

  def tags=(tags)
    super
    __elasticsearch__.index_document
  end

  def as_indexed_json(_ = nil)
    as_json(include: { tags: { only: :content } }, except:  %i[id _id])
  end

  def display_name
    "photo ##{id}"
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :album, through: :user
  load_and_authorize_resource through: :album

  def new
  end

  def show
    @comments = @photo.comments.includes(:user)
    @tags = @photo.tags
  end

  def edit
  end

  def update
    @photo.tags = TagService.new(params[:photo][:tags]).tags if @photo.update_attributes(photo_params)
    photo_respond
  end

  def create
    @photo.tags = TagService.new(params[:photo][:tags]).tags if @photo.save
    photo_respond
  end

  def destroy
    @photo.destroy
    photo_respond
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :description)
  end

  def photo_respond
    respond_with @photo, location: -> { user_album_path(@user, @album) }
  end
end

app/views/photos/_feed_photo.html.slim
- model_class = Photo
- @feed_photos.each do |photo|
  .feed-photo
    .photo-border
      = link_to user_album_photo_path(photo.album.user, photo.album, photo), remote: true
        = image_tag photo.image.thumb, class: 'img-responsive center-block'
    .flex-feed
      div
        |User: 
        = link_to user_path(photo.album.user)
          - if photo.album.user.avatar.url.present?
            = image_tag photo.album.user.avatar, class: 'photo-preview'
          - else
            = image_tag '/avatar_empty.png', class: 'photo-preview'
        |   
        = link_to "#{photo.album.user.display_name}", photo.album.user
      div
        |Album: 
        = link_to "#{photo.album.title}", user_album_path(photo.album.user, photo.album)

app/views/photos/_form.html.slim
- tags = @photo.tags.map { |tag| { id: tag.content, text: tag.content , selected: true } }
.col-md-6.col-md-offset-3
  = simple_form_for @photo, url: url do |f|
    = f.error_notification
    .form-inputs
      .center.photo-border
        - if @photo.image.thumb.url.present?
          = image_tag @photo.image.thumb, class: 'img-responsive center-block'
      .field
        = f.label :image do
          = f.error :image
          = f.file_field :image
          = f.hidden_field :image_cache
      = f.input :tags, as: :select, input_html: { id: 'tags', multiple: true,
                                                  data: { tags: tags, width: '100%' } },
                                                  collection: [], include_blank: false,
                                                  include_hidden: false
      = f.input :description
    .form-actions.flex-buttons
      = link_to "Back", :back, class: 'btn btn-default'
      = f.button :submit, class: 'btn btn-success'

app/views/photos/_photo.html.slim
- model_class = Photo
.col-md-6.photo_description
  .photo-border
    =link_to user_album_photo_path(photo.album.user, photo.album, photo), remote: true
      = image_tag photo.image.thumb, class: 'img-responsive center-block'

app/views/photos/_show.html.slim
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      h3.modal-title.flex-buttons
        - if can? :update, @photo
          = link_to "Edit Photo", edit_user_album_photo_path(@user, @album, @photo), class: 'btn btn-default'
        = @photo.description
        - if can? :destroy, @album, @photo
          = link_to "Delete Photo", user_album_photo_path(@user, @album, @photo), method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'btn btn-danger'
    .modal-body
      .row
        .col-md-9.photo-border
          = image_tag @photo.image, class: 'img-responsive center-block'
        .col-md-3
          .comments-block
            .comments.ScrollStyle
              = render @comments
            = render 'comments/form'
    .modal-footer
      h4.flex-modal-footer
        = render @tags if @tags
        button.btn.btn-danger[type="button" data-dismiss="modal"]
          | Close

app/views/photos/edit.html.slim
- model_class = Photo
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render 'form', url: user_album_photo_path(@user, @album, @photo)

app/views/photos/new.html.slim
- model_class = Photo
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render 'form', url: user_album_photos_path(@user, @album)

app/views/photos/show.html.erb
<%- model_class = Photo -%>

<div class="modal fade" id="modal-1">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" type="button" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal window</h4>
        <div class="modal-body">
          <p>
             <dl class="dl-horizontal">
              <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_user_album_photo_comment_path(@user, @album, @photo), :class => 'btn btn-primary' %>
              <ol class="comments">
                <%= render @comments %>
              </ol>
            </dl>
          </p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

app/views/photos/show.html.slim
- model_class = Photo
.col-md-9.photo-border
  = image_tag @photo.image, class: 'img-responsive center-block'
.col-md-3
  .comments
    = render @comments
    = render 'comments/form'
.modal-footer
  = @photo.description
  = render @tags if @tags

app/views/photos/show.js.slim
  | $(".modal").html('
  = j render(partial: "show", layout: false)
  | ');
  | $(".modal").modal('show');